language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t tstocks/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tstocks/docker-react npm run test
  